[Connection]
#payload_length=100
payload=adsadhiuashdiusahduiashduiashduisah
destination_ip=127.0.0.1
destination_port=5000
source_port=12345
#sending_period rate in ms
sending_period=1000
source_ip=127.0.0.1

[Connection]
payload_length=1024
destination_ip=239.0.0.99
destination_port=5000
sending_period=200

[Connection]
payload_length=652
destination_ip=229.0.0.99
destination_port=615
sending_period=1